name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - run: mypy .
      - run: pytest
